#!/bin/bash

# Let's make really sure that we have correct http proxy settings.
if [ -x $target/usr/share/debian-edu-config/tools/update-proxy-from-wpad ]; then
	chroot $target /usr/share/debian-edu-config/tools/update-proxy-from-wpad
fi
