#!/bin/bash

# Let's make really sure that we have correct http proxy settings.
if [ -x $target/usr/share/debian-edu-config/tools/update-proxy-from-wpad ]; then
	# never fail, this will be repeated during runtime...
	chroot $target /usr/share/debian-edu-config/tools/update-proxy-from-wpad || true
fi
