#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.

# late in the boot process restart autofs(-ldap)...
invoke-rc.d autofs restart

if [ ! -e /usr/local/share/ca-certificates/debian-edu/Debian-Edu_rootCA.crt ] && [ -e /etc/ssl/certs/Debian-Edu_rootCA.crt ]; then

	mkdir -p /usr/local/share/ca-certificates/debian-edu/
	cp /etc/ssl/certs/Debian-Edu_rootCA.crt /usr/local/share/ca-certificates/debian-edu/
	update-ca-certificates

fi

exit 0
