#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.


# workaround until debian-edu-config bug #971780 is fixed...
if [ -e /usr/local/share/ca-certificates/Debian-Edu_rootCA.crt ] && [ ! -h /etc/ssl/certs/Debian-Edu_rootCA.pem ]; then

	update-ca-certificates

fi

exit 0
