#! /bin/bash

# assign classes to hosts based on their hostname

# do not use this if a menu will be presented
[ "$flag_menu" ] && exit 0

# use a list of classes for our demo machine
case $HOSTNAME in
    *)
#           echo "FAIBASE DEBIAN EDU WORKSTATION XORG MATE LVM" ;;
    	    echo "FAIBASE DEBIAN EDU LVM" ;;
esac
