#!/bin/bash

# tag Debian Edu machine as a roaming workstation
if [ -f $target/etc/debian-edu/config ]; then
	sed -i $target/etc/debian-edu/config -e "s/^PROFILE=.*$/PROFILE=\"Roaming-Workstation\"/"

	# reconfigure debian-edu-install to get desktop profiles right
	export DEBIAN_FRONTEND=noninteractive
	chroot $target dpkg-reconfigure debian-edu-install
	unset DEBIAN_FRONTEND
fi
